#!/usr/bin/env Rscript
setwd('~/PSAS/LV3.1bendTest/')
tomDat <- read.csv('Gen2Module StressTest1.txt', skip=5)
names(tomDat) <- c('Row', 'Time', 'Load_kN', 'strain_red', 'strain_laser', 'strain_blue')
plot(tomDat$Time, tomDat$Load_kN, type='l')
plot(tomDat$Time, tomDat$strain_red, type='l')
plot(tomDat$Time, tomDat$strain_laser, type='l')
plot(tomDat$Time, tomDat$strain_blue, type="l")
range(tomDat$Load_kN)
1145*(60.0625^3)*(6+6.65)/(24*(6^3+2*6.65^3))/(4.216e6)
#right_b1 <- read.csv('tracking/block1/')
right_b2 <- read.csv('tracking/block2/right/rightSideCombined2.csv')
#right_b3 <- read.csv('tracking/block3/')
left_b1 <- read.csv('tracking/block1/leftSideCombined1.csv')
left_b2 <- read.csv('tracking/block2/left/leftSideCombined2.csv')
left_b3 <- read.csv('tracking/block3/leftSideCombined3.csv')
names(left_b1)
names(left_b2)
names(left_b3)
intersect(names(left_b1), names(left_b2))
leftDat <- merge(left_b1, left_b2)
